[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "lib/composable-cow:cowprotocol/=lib/composable-cow/lib/cowprotocol/src/contracts/",
  "lib/composable-cow:safe/=lib/composable-cow/lib/safe/contracts/",
  "lib/composable-cow:@openzeppelin/=lib/composable-cow/lib/@openzeppelin/contracts/",
  "lib/composable-cow:@openzeppelin/contracts/=lib/composable-cow/lib/@openzeppelin/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
